# REGION 2: South Region Cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: south-region
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30003
    protocol: TCP
  - containerPort: 30001
    hostPort: 30004
    protocol: TCP
- role: worker
- role: worker
- role: worker
