# CENTRAL ELECTION COMMISSION (CEC) Cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: election-central
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80  # Ingress
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 30000
    hostPort: 30007
    protocol: TCP
- role: worker
- role: worker
- role: worker
- role: worker  # Extra worker for load balancing