apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: election-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.19.0.200-172.19.0.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: election-advertisement
  namespace: metallb-system
